### ISSUE TITLE
Unable to log into PSN

### ISSUE THREAD

**Issue by poppiestar** [cubehouse/PSNjs#1]
I suspect Sony's changed the login process as this was working a few weeks ago, but now it's not.

Using the first example in the README.md (under API setup), I've updated the script to use my PSN email and password but I consistently have the same failure. The log I get is:

[PSN] :: Need to login - no auth token found
[PSN] :: Need to fetch access tokens - tokens expired
[PSN] :: Need to fetch userdata - no region or username available
[PSN] :: Making OAuth Request...
[PSN] :: Logging in...
[PSN] :: Failed to make login request
[PSN] :: Token error: Error: socket hang up
Error fetching trophies: Error: socket hang up

**Comment by cubehouse** [comment]
Seems to be failing on the initial request, and not returning the data expected.
https://github.com/cubehouse/PSNjs/blob/master/psn_request.js#L430

I'm having various issues accessing PSN anyway, so I can't debug this easily at the moment.

Trying to debug by writing the response from the URL somewhere to see what is going on, but I won't have any feedback on that until PSN works for me.

**Comment by poppiestar** [comment]
Hi, not sure if it's useful or not but https://github.com/jhewt/gumer-psn has recently been updated to work with the new login method.

**Comment by cubehouse** [comment]
Resolved with 67b40f3a1749cc024835bacd9f2713ed13027e95
Bumped to new version and pushed to npm.

**Comment by poppiestar** [comment]
Wow, that was insanely fast! Thank you so much, I'll be giving you mad thanks when I finally launch my app! :)
