### ISSUE TITLE
WebSocket Connection to receive new PSN Messages

### ISSUE THREAD

**Issue by j-holub** [cubehouse/PSNjs#4]
Hey there!

Thanks for your great API. I was thinking about using it in the near future. One idea I had was using electron to built a PSN chat client for the desktop.

Do you have any idea where I could start looking to reverse engineer the web socket connection to receive new messages? You can chat on the playstation website so I would assume they use web sockets for that. That would of course by my first point to look at but maybe you remember something more from the work on your module.

**Comment by cubehouse** [comment]
I no longer maintain this project, and haven't made any changes in the last 3 years, so I fear I don't remember any of the implementation details from back then, and I expect the chat you are talking of didn't exist back then.

**Comment by j-holub** [comment]
I was aware from your message on the other issue that you're not maintaining this project anymore. I just thought you might have some advice :)

Thanks anyway!
